name: Manual Harmony Pipeline CD Trigger

on:
  workflow_dispatch:

jobs:
  call_workflow:
    uses: dwanim/.github/.github/workflows/Harmony_CICD.yml@master
    with:
      pipe_config: 'release'
      rez_config: 'rez-2'
