name: Show Lock Harmony Pipeline CD Trigger

on:
  workflow_dispatch:
  push:
    branches:
      - '**lock'

jobs:
  rerelease_package:
    runs-on: [self-hosted, rez]
    steps:
      - name: Launch Action
        uses: CM/cm-actions/pipeline_trigger@main
        with:
          pipe_config: 'release'
          rez_config: 'rez-2'
