name: Create Test Map

on:
  workflow_dispatch:
    inputs:
      testmappath:
        description: 'Path to release test map under.'
        required: true
        type: string

jobs:
  create_testmap:
    runs-on: [self-hosted, rez]
    steps:
      - name: Launch Action
        uses: CM/cm-actions/pipeline_trigger@main
        with:
          pipe_config: 'pre-release'
          rez_config: 'rez-2'
          pipe_args: 'custom_release_packages_path=${{ github.event.inputs.testmappath }}'
